//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Zapasnojj_parkomat2
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Запись.
    /// </summary>
    [TrimmedStringStorage(false)]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("ЗаписьE", new string[] {
            "Стоимость as \'Стоимость\'",
            "Автомобиль as \'Автомобиль\'",
            "Автомобиль.ГосНомер as \'Гос номер\'",
            "ПаркМесто as \'Парковочное место\'",
            "ПаркМесто.Номер as \'Номер\'",
            "Услуга as \'Услуга\'",
            "Услуга.Длительность as \'Длительность\'"}, Hidden=new string[] {
            "Автомобиль.ГосНомер",
            "ПаркМесто.Номер",
            "Услуга.Длительность"})]
    [MasterViewDefineAttribute("ЗаписьE", "Автомобиль", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "ГосНомер")]
    [MasterViewDefineAttribute("ЗаписьE", "ПаркМесто", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "Номер")]
    [MasterViewDefineAttribute("ЗаписьE", "Услуга", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "Длительность")]
    public class Запись : ICSSoft.STORMNET.DataObject
    {
        
        private double fСтоимость;
        
        private IIS.Zapasnojj_parkomat2.Автомобиль fАвтомобиль;
        
        private IIS.Zapasnojj_parkomat2.ПаркМесто fПаркМесто;
        
        private IIS.Zapasnojj_parkomat2.Услуга fУслуга;
        
        private IIS.Zapasnojj_parkomat2.Паркомат fПаркомат;
        
        /// <summary>
        /// Стоимость.
        /// </summary>
        // *** Start programmer edit section *** (Запись.Стоимость CustomAttributes)

        // *** End programmer edit section *** (Запись.Стоимость CustomAttributes)
        public virtual double Стоимость
        {
            get
            {
                // *** Start programmer edit section *** (Запись.Стоимость Get start)

                // *** End programmer edit section *** (Запись.Стоимость Get start)
                double result = this.fСтоимость;
                // *** Start programmer edit section *** (Запись.Стоимость Get end)

                // *** End programmer edit section *** (Запись.Стоимость Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Запись.Стоимость Set start)

                // *** End programmer edit section *** (Запись.Стоимость Set start)
                this.fСтоимость = value;
                // *** Start programmer edit section *** (Запись.Стоимость Set end)

                // *** End programmer edit section *** (Запись.Стоимость Set end)
            }
        }
        
        /// <summary>
        /// Запись.
        /// </summary>
        // *** Start programmer edit section *** (Запись.Автомобиль CustomAttributes)

        // *** End programmer edit section *** (Запись.Автомобиль CustomAttributes)
        [PropertyStorage(new string[] {
                "Автомобиль"})]
        [NotNull()]
        public virtual IIS.Zapasnojj_parkomat2.Автомобиль Автомобиль
        {
            get
            {
                // *** Start programmer edit section *** (Запись.Автомобиль Get start)

                // *** End programmer edit section *** (Запись.Автомобиль Get start)
                IIS.Zapasnojj_parkomat2.Автомобиль result = this.fАвтомобиль;
                // *** Start programmer edit section *** (Запись.Автомобиль Get end)

                // *** End programmer edit section *** (Запись.Автомобиль Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Запись.Автомобиль Set start)

                // *** End programmer edit section *** (Запись.Автомобиль Set start)
                this.fАвтомобиль = value;
                // *** Start programmer edit section *** (Запись.Автомобиль Set end)

                // *** End programmer edit section *** (Запись.Автомобиль Set end)
            }
        }
        
        /// <summary>
        /// Запись.
        /// </summary>
        // *** Start programmer edit section *** (Запись.ПаркМесто CustomAttributes)

        // *** End programmer edit section *** (Запись.ПаркМесто CustomAttributes)
        [PropertyStorage(new string[] {
                "ПаркМесто"})]
        [NotNull()]
        public virtual IIS.Zapasnojj_parkomat2.ПаркМесто ПаркМесто
        {
            get
            {
                // *** Start programmer edit section *** (Запись.ПаркМесто Get start)

                // *** End programmer edit section *** (Запись.ПаркМесто Get start)
                IIS.Zapasnojj_parkomat2.ПаркМесто result = this.fПаркМесто;
                // *** Start programmer edit section *** (Запись.ПаркМесто Get end)

                // *** End programmer edit section *** (Запись.ПаркМесто Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Запись.ПаркМесто Set start)

                // *** End programmer edit section *** (Запись.ПаркМесто Set start)
                this.fПаркМесто = value;
                // *** Start programmer edit section *** (Запись.ПаркМесто Set end)

                // *** End programmer edit section *** (Запись.ПаркМесто Set end)
            }
        }
        
        /// <summary>
        /// Запись.
        /// </summary>
        // *** Start programmer edit section *** (Запись.Услуга CustomAttributes)

        // *** End programmer edit section *** (Запись.Услуга CustomAttributes)
        [PropertyStorage(new string[] {
                "Услуга"})]
        [NotNull()]
        public virtual IIS.Zapasnojj_parkomat2.Услуга Услуга
        {
            get
            {
                // *** Start programmer edit section *** (Запись.Услуга Get start)

                // *** End programmer edit section *** (Запись.Услуга Get start)
                IIS.Zapasnojj_parkomat2.Услуга result = this.fУслуга;
                // *** Start programmer edit section *** (Запись.Услуга Get end)

                // *** End programmer edit section *** (Запись.Услуга Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Запись.Услуга Set start)

                // *** End programmer edit section *** (Запись.Услуга Set start)
                this.fУслуга = value;
                // *** Start programmer edit section *** (Запись.Услуга Set end)

                // *** End programmer edit section *** (Запись.Услуга Set end)
            }
        }
        
        /// <summary>
        /// мастеровая ссылка на шапку IIS.Zapasnojj_parkomat2.Паркомат.
        /// </summary>
        // *** Start programmer edit section *** (Запись.Паркомат CustomAttributes)

        // *** End programmer edit section *** (Запись.Паркомат CustomAttributes)
        [Agregator()]
        [NotNull()]
        [PropertyStorage(new string[] {
                "Паркомат"})]
        public virtual IIS.Zapasnojj_parkomat2.Паркомат Паркомат
        {
            get
            {
                // *** Start programmer edit section *** (Запись.Паркомат Get start)

                // *** End programmer edit section *** (Запись.Паркомат Get start)
                IIS.Zapasnojj_parkomat2.Паркомат result = this.fПаркомат;
                // *** Start programmer edit section *** (Запись.Паркомат Get end)

                // *** End programmer edit section *** (Запись.Паркомат Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Запись.Паркомат Set start)

                // *** End programmer edit section *** (Запись.Паркомат Set start)
                this.fПаркомат = value;
                // *** Start programmer edit section *** (Запись.Паркомат Set end)

                // *** End programmer edit section *** (Запись.Паркомат Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "ЗаписьE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ЗаписьE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ЗаписьE", typeof(IIS.Zapasnojj_parkomat2.Запись));
                }
            }
        }
    }
    
    /// <summary>
    /// Detail array of Запись.
    /// </summary>
    public class DetailArrayOfЗапись : ICSSoft.STORMNET.DetailArray
    {
        
        // *** Start programmer edit section *** (IIS.Zapasnojj_parkomat2.DetailArrayOfЗапись members)

        // *** End programmer edit section *** (IIS.Zapasnojj_parkomat2.DetailArrayOfЗапись members)

        
        /// <summary>
        /// Construct detail array.
        /// </summary>
        /// <summary>
        /// Returns object with type Запись by index.
        /// </summary>
        /// <summary>
        /// Adds object with type Запись.
        /// </summary>
        public DetailArrayOfЗапись(IIS.Zapasnojj_parkomat2.Паркомат fПаркомат) : 
                base(typeof(Запись), ((ICSSoft.STORMNET.DataObject)(fПаркомат)))
        {
        }
        
        public IIS.Zapasnojj_parkomat2.Запись this[int index]
        {
            get
            {
                return ((IIS.Zapasnojj_parkomat2.Запись)(this.ItemByIndex(index)));
            }
        }
        
        public virtual void Add(IIS.Zapasnojj_parkomat2.Запись dataobject)
        {
            this.AddObject(((ICSSoft.STORMNET.DataObject)(dataobject)));
        }
    }
}
