//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Zapasnojj_parkomat2
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Терминал.
    /// </summary>
    [TrimmedStringStorage(false)]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("ТерминалE", new string[] {
            "НомерТер as \'Номер терминала\'"})]
    [View("ТерминалL", new string[] {
            "НомерТер as \'Номер терминала\'"})]
    public class Терминал : ICSSoft.STORMNET.DataObject
    {
        
        private int fНомерТер;
        
        /// <summary>
        /// НомерТер.
        /// </summary>
        // *** Start programmer edit section *** (Терминал.НомерТер CustomAttributes)

        // *** End programmer edit section *** (Терминал.НомерТер CustomAttributes)
        public virtual int НомерТер
        {
            get
            {
                // *** Start programmer edit section *** (Терминал.НомерТер Get start)

                // *** End programmer edit section *** (Терминал.НомерТер Get start)
                int result = this.fНомерТер;
                // *** Start programmer edit section *** (Терминал.НомерТер Get end)

                // *** End programmer edit section *** (Терминал.НомерТер Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Терминал.НомерТер Set start)

                // *** End programmer edit section *** (Терминал.НомерТер Set start)
                this.fНомерТер = value;
                // *** Start programmer edit section *** (Терминал.НомерТер Set end)

                // *** End programmer edit section *** (Терминал.НомерТер Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "ТерминалE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ТерминалE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ТерминалE", typeof(IIS.Zapasnojj_parkomat2.Терминал));
                }
            }
            
            /// <summary>
            /// "ТерминалL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ТерминалL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ТерминалL", typeof(IIS.Zapasnojj_parkomat2.Терминал));
                }
            }
        }
    }
}
